trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: subscriptionId
  displayName: The subscription id to deploy your resources to
  type: string
- name: resourceGroupName
  displayName: The resource group name to deploy your resources to
  type: string
- name: location
  displayName: The location your resources to
  type: string
- name: serviceConnectionName
  displayName: The service connection name to use to deploy your resources
  type: string
- name: deployAIBTemplate
  displayName: Deploy Azure Image Builder template
  type: boolean
  default: true

jobs:
- job: CheckforChangesJob
  displayName: Check if template redeployment is required
  workspace:
    clean: all
  steps:
  - task: PowerShell@2
    name: CheckForChangesTask
    displayName: Check for code changes requiring template redeployment
    inputs:
      pwsh: true
      targetType: "inline"
      script: |
        Write-Host "Checking for code changes requiring template redeployment..."
        $result = & "$(Build.SourcesDirectory)/Deployment/Get-CodeChanges.ps1" `
                -DeploymentBicepFilePath "$(Build.SourcesDirectory)/IaC/BringYourOwnResources/aib.bicep" `
                -ParametersFilePath "$(Build.SourcesDirectory)/IaC/BringYourOwnResources/aib.parameters.json" `
                -GitRepositoryPath "$(Build.SourcesDirectory)"

        if ($result -eq $true) {
          Write-Host "##vso[task.setvariable variable=templateRedeploymentRequired;isReadOnly=true;isOutput=true]true"
        }
        else {
          Write-Host "##vso[task.setvariable variable=templateRedeploymentRequired;isReadOnly=true;isOutput=true]false"
        }
- job: DeployAndRunJob
  displayName: Deploy and run template
  dependsOn: CheckforChangesJob
  workspace:
    clean: all
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    name: DeployBicep
    displayName: Deploy Bicep template
    condition: eq(dependencies.CheckforChangesJob.outputs['CheckForChangesTask.templateRedeploymentRequired'], 'true')
    inputs:
      deploymentScope: "Resource Group"
      connectedServiceName: "${{ parameters.serviceConnectionName }}"
      subscriptionId: "${{ parameters.subscriptionId }}"
      action: "Create Or Update Resource Group"
      deploymentMode: "Incremental"
      resourceGroupName: "${{ parameters.resourceGroupName }}"
      location: "${{ parameters.location }}"
      templateLocation: "Linked artifact"
      csmFile: "$(Build.SourcesDirectory)/IaC/BringYourOwnResources/aib.bicep"
      csmParametersFile: "$(Build.SourcesDirectory)/IaC/BringYourOwnResources/aib.parameters.json"
      deploymentOutputs: deploymentOutputs
  # see https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureResourceManagerTemplateDeploymentV3#deployment-outputs
  - task: PowerShell@2
    name: SetOutputs
    displayName: Set Outputs from Bicep deployment
    condition: eq(dependencies.CheckforChangesJob.outputs['CheckForChangesTask.templateRedeploymentRequired'], 'true')
    inputs:
      pwsh: true
      targetType: "inline"
      script: |
        $outputs = ConvertFrom-Json "$(DeployBicep.deploymentOutputs)"
        Write-Host "##vso[task.setvariable variable=imageTemplateName;isReadOnly=true]$outputs.imageTemplateName.value"
  - task: PowerShell@2
    name: Extract Image Template name
    condition: eq(dependencies.CheckforChangesJob.outputs['CheckForChangesTask.templateRedeploymentRequired'], 'false')
    inputs:
      pwsh: true
      targetType: "inline"
      script: |
        $parameters = Get-Content -Raw "$(Build.SourcesDirectory)/IaC/BringYourOwnResources/aib.parameters.json" | Convert-FromJson
        $imageTemplateName = $parameters.parameters.imageTemplateName.value
        Write-Host "##vso[task.setvariable variable=imageTemplateName;isReadOnly=true]$imageTemplateName"
  - task: AzurePowerShell@5
    name: RunTemplate
    displayName: Run Image template
    inputs:
      pwsh: true
      azureSubscription: "${{ parameters.serviceConnectionName }}"
      azurePowerShellVersion: LatestVersion
      scriptType: "filePath"
      scriptPath: "$(Build.SourcesDirectory)/Deployment/Invoke-ImageTemplate.ps1"
      scriptArguments:
        -ImageTemplateName "$(imageTemplateName)" `
        -ResourceGroupName "${{ parameters.resourceGroupName }}"
        -OutputLogs `
        -KeepImageBuilderTemplate $TRUE
      informationPreference: "continue"
      errorActionPreference: "stop"