name: Deploy and Run Image Template

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  LOCATION: ${{ vars.LOCATION }}

jobs:
  deploy-and-run:
    name: Deploy and Run Template
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # see https://github.com/azure/bicep-deploy
    - name: Deploy Bicep Template
      id: deploy_bicep
      uses: azure/bicep-deploy@v2
      with:
        type: deployment
        operation: create
        scope: resourceGroup
        name: devbox-imagetemplate-deployment
        location: ${{ env.LOCATION }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resource-group-name: ${{ env.RESOURCE_GROUP_NAME }}
        template-file: ./IaC/aib.bicep
        parameters-file: ./IaC/aib.parameters.json
        deploymentMode: Incremental

    - name: Azure PowerShell script
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          ./Deployment/Invoke-ImageTemplate.ps1 `
          -ImageTemplateName ${{ steps.deploy_bicep.outputs.imageTemplate }} `
          -ResourceGroupName ${{ env.RESOURCE_GROUP_NAME }}